spring:
  application:
    name: dcm
  iot-datasource:
    jdbc-url: jdbc:mariadb://192.168.167.221:3306/iot?serverTimezone=Asi
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver
  svc-datasource:
    jdbc-url: jdbc:mariadb://192.168.167.221:3306/svc?serverTimezone=Asi
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 80


